### ISSUE TITLE
v1.1 with_tool, tacotron2模型, 点击合成语音 无反应

### ISSUE THREAD

**Issue by jieran233** [luoyily/MoeTTS#13]
如题（不是假死，是没有反应）

**Comment by luoyily** [comment]
应该是cleaners导入依赖错误，下个版本修复。

**Comment by luoyily** [comment]
另外请提供控制台报错信息

**Comment by jieran233** [comment]
> 另外请提供控制台报错信息

抱歉刚才没留意控制台，这是控制台报错：
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "moe_tts_cpu_tool.py", line 324, in <lambda>
  File "moe_tts_cpu_tool.py", line 90, in inference_taco
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "tacotron2\hparams.py", line 4, in <module>
  File "./custom\tacotext\__init__.py", line 3, in <module>
    from tacotext import cleaners
  File "./custom\tacotext\cleaners.py", line 16, in <module>
    from unidecode import unidecode
ModuleNotFoundError: No module named 'unidecode'
```

**Comment by jieran233** [comment]
啊这，不小心close了

**Comment by luoyily** [comment]
已确认为cleaners加载依赖错误，下个版本会修复，你也可以将cleaners.py中的from unidecode import unidecode，以及用到unidecode的函数注释掉暂时使用。

**Comment by luoyily** [comment]
已发布新的release，修复了这个问题
