### ISSUE TITLE
无法识别数字音标

### ISSUE THREAD

**Issue by Stardust-minus** [luoyily/MoeTTS#14]
如题。
我在VITS模型上做训练，使用的是已经过clean的训练集，使用拼音+数字音标
![image](https://user-images.githubusercontent.com/52093397/184044885-fba46313-63eb-441c-9e66-5da6fe684187.png)
但在导入MoeTTS时无法合成，尝试合成验证集里的一句话 dui4 o2 ni3 bu2 shi zai4 cheng2 li3 ma
报错

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "moe_tts_cpu_tool.py", line 365, in <lambda>
  File "moe_tts_cpu_tool.py", line 185, in inference_vitss
  File "moe_tts_cpu_tool.py", line 153, in synthesis
  File "moe_tts_cpu_tool.py", line 143, in get_text
  File "./custom\vitstext\__init__.py", line 25, in text_to_sequence
    symbol_id = _symbol_to_id[symbol]
KeyError: '2'

**Comment by Stardust-minus** [comment]
强改了一下cleaner
现在报错变成这样了
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "moe_tts_cpu_tool.py", line 365, in <lambda>
  File "moe_tts_cpu_tool.py", line 183, in inference_vitss
  File "moe_tts_cpu_tool.py", line 153, in synthesis
  File "moe_tts_cpu_tool.py", line 143, in get_text
  File "./custom\vitstext\__init__.py", line 23, in text_to_sequence
    clean_text = _clean_text(text, cleaner_names)
  File "./custom\vitstext\__init__.py", line 53, in _clean_text
    cleaner = getattr(cleaners, name)
AttributeError: module 'vitstext.cleaners' has no attribute 'c'

**Comment by luoyily** [comment]
见 [Readme](https://github.com/luoyily/MoeTTS#%E8%87%AA%E5%AE%9A%E4%B9%89cleaner%E4%B8%8Esymbols)
