### ISSUE TITLE
关于MoeTTS运行过程中遇见的问题

### ISSUE THREAD

**Issue by Exiam6** [luoyily/MoeTTS#23]
大佬您好，我最近在用tacotron2训练命运石之门中助手的语音模型，然后想用您写的软件转换成语音输出，可是在运行过程中产生了如下报错
然后我又下载了您提供的Atri的文件试着跑了一遍，发现也产生了同样的报错
请问如何解决这种情况呢？ 

报错如下：
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "moe_tts_cpu_beta.py", line 455, in <lambda>
  File "moe_tts_cpu_beta.py", line 167, in inference_taco
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "tacotron2\hparams.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "tensorflow\__init__.py", line 99, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "tensorflow_core\__init__.py", line 771, in <module>
  File "tensorflow_core\__init__.py", line 769, in _running_from_pip_package
  File "tensorflow_core\__init__.py", line 769, in <genexpr>
TypeError: startswith first arg must be str or a tuple of str, not NoneType

**Comment by luoyily** [comment]
已了解该问题，应该是pyinstaller打包后在部分系统上没能适配tensorflow库导致导入失败，下版本(近几天会有)将移除此依赖以及尝试其他编译器，应该能解决这个问题，并减小体积加快运行速度。

**Comment by Exiam6** [comment]
非常感激！

**Comment by luoyily** [comment]
我在新版中移除了tensorflow依赖并优化了代码，可以试下新版能否正常运行

**Comment by Exiam6** [comment]
您好！我刚刚下载了新版的软件，并运行了Atri的tacotron与hifi模型，出现了如下新的报错：
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "moe_tts_cpu.py", line 369, in <lambda>
  File "moe_tts_cpu.py", line 200, in inference_taco
  File "moe_tts_cpu.py", line 181, in synthesis
  File "tacotron2\model.py", line 520, in inference
  File "tacotron2\model.py", line 195, in inference
  File "torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "tacotron2\layers.py", line 40, in forward
  File "torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "torch\nn\modules\conv.py", line 307, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "torch\nn\modules\conv.py", line 304, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Calculated padded input size per channel: (4). Kernel size: (5). Kernel size can't be greater than actual input size
请问如何解决呢？

**Comment by luoyily** [comment]
我这边在两个win10系统(Win 10 20H2 19042.1052/Win 10 22H2_19045.1806)上测试似乎没出现此问题，希望提供下你的系统版本，以及你输入的文本。

**Comment by Exiam6** [comment]
问题已经解决了！
我的文本输入格式之前有误，这次我改成了罗马音输入之后得到了十分完美的结果
非常感激！
